[platformio]
default_envs = protocols

[env:protocols]
platform = symlink://C:/Users/User/.platformio/platforms/espressif32
board = esp-wrover-kit
framework = espidf
upload_speed = 460800
board_build.flash_mode = dio
board_build.f_flash = 40000000L
board_upload.flash_size = 4MB
board_build.sdkconfig_defaults = sdkconfig.defaults
