[env:freenove-wrover]
; Use the already installed, inspected platform and Arduino 3.3.8 packages.
platform = symlink://C:/Users/User/.platformio/platforms/espressif32
board = esp-wrover-kit
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_build.flash_mode = dio
board_build.f_flash = 40000000L
board_upload.flash_size = 4MB

