"""Offline strict all-32-channel native Stream CSV/.demo consistency analysis.

Only completed hash-anchored exports are compared. Actual declared capture N
is separate from requested duration: immediate Stream stop can change N.
No USB, GUI, generator, firmware, or archived analyzer is modified.
"""

import argparse
import csv
from decimal import Decimal
import hashlib
import json
from pathlib import Path
import re
import tempfile
import zipfile

from analyze_duty_capture import analyze_levels, capture_sha256
from native_buffer_analyze import inspect_demo, parse_quantity, read_native_csv


CHANNELS = tuple(range(32))
RATE = 50000000
BLOCK_BYTES = 1048576
BLOCK_SAMPLES = BLOCK_BYTES * 8
DATA_MAPPING = "18446744073709551614,0"
LOW_MAPPING = "18446744073709551615,0"
BYTE_LEVELS = tuple(bytes((value >> bit) & 1 for bit in range(8)) for value in range(256))


class UnsupportedRepresentation(ValueError):
    """An unverified storage mapping must stay pending, never be guessed."""


class PendingExports(ValueError):
    """No explicit completion marker authorizes sample comparison."""


def require(condition, message):
    if not condition:
        raise ValueError(message)


def json_read(path):
    return json.loads(path.read_text(encoding="utf-8-sig"))


def marker_inputs(marker_path):
    marker = json_read(marker_path)
    if marker.get("completed") is not True:
        raise PendingExports("Marker does not confirm completed exports")
    def anchored(name):
        path = Path(marker[name])
        path = path if path.is_absolute() else marker_path.parent / path
        expected = marker.get(name + "_sha256")
        require(isinstance(expected, str) and re.fullmatch(r"[0-9a-fA-F]{64}", expected),
                f"Marker lacks direct anchored {name} SHA256")
        require(path.is_file(), f"Completed {name} is missing")
        require(capture_sha256(path) == expected.lower(),
                f"{name} hash differs from completion marker; no sample comparison performed")
        return path, expected.lower()
    csv_path, csv_sha = anchored("csv")
    demo_path, demo_sha = anchored("demo")
    return marker, csv_path, csv_sha, demo_path, demo_sha


def set_high_span(payload, start, end):
    """Set an LSB-first bit interval; all spans are disjoint, initially zero."""
    if start >= end:
        return
    first, last = start // 8, (end - 1) // 8
    if first == last:
        payload[first] |= ((1 << (end - start)) - 1) << (start % 8)
        return
    payload[first] |= (255 << (start % 8)) & 255
    if last > first + 1:
        payload[first + 1:last] = b"\xff" * (last - first - 1)
    payload[last] |= (1 << ((end - 1) % 8 + 1)) - 1


def read_csv_packed(path):
    """Frozen parser's rules, streaming input into N/8 bytes per channel."""
    headers = {}
    with path.open("r", encoding="utf-8-sig", newline="") as source:
        for line in source:
            if line.startswith(";"):
                text = line[1:].strip()
                if ":" in text and not text.startswith("CSV, generated by "):
                    key, value = text.split(":", 1)
                    key = key.strip()
                    require(key not in headers, f"Duplicate CSV metadata key: {key}")
                    headers[key] = value.strip()
                continue
            if line.strip():
                header = next(csv.reader([line], skipinitialspace=True))
                break
        else:
            raise ValueError("CSV contains no event header")
        require([item.strip() for item in header[:2]] == ["SystemTime", "Time(s)"],
                "Expected official waveform event CSV header")
        columns = {}
        for column, label in enumerate(header[2:], 2):
            match = re.fullmatch(r"channel\s+(\d+)", label.strip())
            require(match and int(match[1]) not in columns, "Ambiguous physical CSV columns")
            columns[int(match[1])] = column
        require(tuple(sorted(columns)) == CHANNELS, "CSV must contain exactly all 32 physical channels")
        rate = parse_quantity(headers["Sample rate"], rate=True)
        samples = parse_quantity(headers["Sample count"])
        if samples > BLOCK_SAMPLES:
            raise UnsupportedRepresentation(
                f"CSV declares {samples} samples; mapping beyond first {BLOCK_SAMPLES} samples is unverified")
        packed = [bytearray((samples + 7) // 8) for _ in CHANNELS]
        states = None
        starts = [0] * 32
        highs = [0] * 32
        transitions = [0] * 32
        first_rising, first_falling = [None] * 32, [None] * 32
        previous_index, previous_row, events = -1, None, 0
        for row_number, row in enumerate(csv.reader(source, skipinitialspace=True), 1):
            if not row or all(not item.strip() for item in row):
                continue
            require(len(row) == len(header), f"CSV event {row_number}: wrong column count")
            exact_index = Decimal(row[1].strip()) * rate
            require(exact_index == int(exact_index), f"CSV event {row_number}: timestamp off sample grid")
            index = int(exact_index)
            require(0 <= index <= samples and index >= previous_index,
                    f"CSV event {row_number}: non-monotone or outside declared capture")
            full = tuple(int(item.strip()) for item in row[2:])
            require(all(value in (0, 1) for value in full), f"CSV event {row_number}: non-binary state")
            if index == previous_index:
                require(full == previous_row, "Conflicting CSV states at same sample")
                continue
            values = tuple(int(row[columns[channel]].strip()) for channel in CHANNELS)
            if states is None:
                require(index == 0, "CSV does not establish sample-0 initial states")
                states = list(values)
            else:
                for channel, value in enumerate(values):
                    if value == states[channel]:
                        continue
                    if states[channel]:
                        set_high_span(packed[channel], starts[channel], index)
                        highs[channel] += index - starts[channel]
                    starts[channel] = index
                    states[channel] = value
                    if index < samples:
                        transitions[channel] += 1
                        destination = first_rising if value else first_falling
                        if destination[channel] is None:
                            destination[channel] = index
            previous_index, previous_row = index, full
            events += 1
        require(states is not None, "CSV has no sample states")
        for channel in CHANNELS:
            if states[channel]:
                set_high_span(packed[channel], starts[channel], samples)
                highs[channel] += samples - starts[channel]
    activity = [{"channel": channel, "initial_level": packed[channel][0] & 1,
                 "transitions": transitions[channel], "high_samples": highs[channel],
                 "low_samples": samples - highs[channel], "constant": transitions[channel] == 0,
                 "first_rising_sample": first_rising[channel], "first_falling_sample": first_falling[channel],
                 "first_frame_levels": [(packed[channel][index // 8] >> (index % 8)) & 1
                                        for index in range(min(8, samples))]}
                for channel in CHANNELS]
    return packed, rate, {"headers": headers, "sample_count": samples, "event_rows": events,
                           "last_event_sample": previous_index, "physical_channels": list(CHANNELS),
                           "sample_count_provenance": "native_CSV_declared_not_independent_USB_count",
                           "time_grid_validation": "every_event_exact_integer_sample",
                           "reconstruction": "sample_0_state_held_until_next_event_or_declared_end",
                           "actual_declared_duration_ms": samples * 1000 / rate}, activity


def validate_configuration(metadata, demo, rate):
    require(demo.get("zip_container") is True, "Expected native demo ZIP container")
    session, config = demo["session_metadata"], demo["saved_configuration"]
    settings = config["settingData"]
    samples = metadata["sample_count"]
    require(rate == RATE and int(session["SamplingFrequency"]) * 1000 == rate,
            "Expected CSV and demo Fs=50 MS/s (native session frequency uses kHz)")
    require(int(session["SamplingDepth"]) == samples, "CSV N differs from demo logical SamplingDepth")
    require(Decimal(str(settings["setHz"])) == rate, "Saved setHz differs from CSV Fs")
    require(settings["isBuffer"] is False and settings["RLE"] is False,
            "Expected Stream with RLE disabled")
    require(Decimal(str(settings["thresholdLevel"])) == Decimal("1.6"), "Expected saved threshold 1.6 V")
    require(config["isSimpleTrigger"] is True and config["isAdvancedTrigger"] is False,
            "Expected Simple trigger configuration")
    require(config["glitchRemoval"] == [], "Glitch removal is present")
    channel_settings = config["channelsSet"]
    require(len(channel_settings) == 32 and all(item["id"] == index and item["enable"] is True
            for index, item in enumerate(channel_settings)), "All 32 inputs must be enabled")
    require(channel_settings[0]["triggerType"] == 1 and all(
        item["triggerType"] == 0 for item in channel_settings[1:]), "Expected D0 rising only")
    requested_ms = Decimal(str(settings["setTime"]))
    require(requested_ms > 0, "Requested duration must be positive")
    return {"mode": "Stream", "Fs_hz": rate, "actual_declared_logical_samples": samples,
            "actual_declared_duration_ms": samples * 1000 / rate,
            "requested_duration_ms": str(requested_ms),
            "requested_nominal_samples_from_rate_duration": str(requested_ms * rate / 1000),
            "requested_vs_actual_N_equality_not_required": True,
            "threshold_volts_saved": settings["thresholdLevel"], "trigger": "D0 rising",
            "trigger_scope": "saved_configuration_not_independent_hardware_trigger_validation",
            "saved_trigger_position_percent": settings.get("triggerPosition"),
            "saved_trigger_depth_samples": session.get("TriggerSamplingDepth"),
            "trigger_depth_percent_equation_not_required_for_Stream": True,
            "isOne_saved": config.get("isOne"), "isInstantly_saved": config.get("isInstantly"),
            "isRoll_saved": config.get("isRoll"), "isStopModeImmediate_saved": config.get("isStopModeImmediate"),
            "Single_acquisition_not_required_for_Stream": True, "RLE": False,
            "all_32_channels_enabled": True, "glitch_removal_disabled": True,
            "saved_PWM_settings_are_not_hardware_readback": config.get("pwmData")}


def compare_packed(expected, actual, samples):
    length = (samples + 7) // 8
    require(len(actual) >= length, "Demo bit allocation is truncated before logical extent")
    mask = (1 << (samples % 8)) - 1 if samples % 8 else 255
    if expected[:-1] == actual[:length - 1] and (expected[-1] ^ actual[length - 1]) & mask == 0:
        return {"compared_logical_samples": samples, "mismatch_count": 0,
                "first_mismatch_sample": None, "last_mismatch_sample": None}
    count, first, last = 0, None, None
    for offset, wanted in enumerate(expected):
        difference = wanted ^ actual[offset]
        if offset == length - 1:
            difference &= mask
        if difference:
            count += difference.bit_count()
            if first is None:
                first = offset * 8 + (difference & -difference).bit_length() - 1
            last = offset * 8 + difference.bit_length() - 1
    return {"compared_logical_samples": samples, "mismatch_count": count,
            "first_mismatch_sample": first, "last_mismatch_sample": last}


def compare_demo(archive, demo, packed, samples):
    names = archive.namelist()
    require(len(set(names)) == len(names), "Duplicate ZIP member names are ambiguous")
    plans = []
    for channel in CHANNELS:
        storage = demo["channel_storage_metadata"][str(channel)]
        if storage["start_sample"] != 0:
            raise UnsupportedRepresentation(f"D{channel}: nonzero native start_sample mapping is unverified")
        require(storage["stored_samples"] >= samples, f"D{channel}: stored count shorter than logical CSV")
        if storage["stored_samples"] > BLOCK_SAMPLES:
            raise UnsupportedRepresentation(f"D{channel}: stored extent spans unverified additional blocks")
        allocation = archive.read(f"{channel}/channel.ini").decode("utf-8-sig").splitlines()[3:]
        require(allocation, f"D{channel}: missing block allocation mapping")
        if any(value != LOW_MAPPING for value in allocation[1:]):
            raise UnsupportedRepresentation(f"D{channel}: additional DATA/HIGH/unknown allocation mapping is unverified")
        mapping = allocation[0]
        member = f"{channel}/0-0.bin"
        extra_members = [name for name in names if name.startswith(f"{channel}/")
                         and name.endswith(".bin") and name != member]
        if extra_members:
            raise UnsupportedRepresentation(f"D{channel}: additional data members require a verified mapping: {extra_members}")
        if mapping == DATA_MAPPING:
            require(member in names, f"D{channel}: allocated data member missing")
            require(archive.getinfo(member).file_size == BLOCK_BYTES,
                    f"D{channel}: truncated or unexpected data allocation length")
        elif mapping == LOW_MAPPING:
            require(member not in names, f"D{channel}: constant-LOW metadata conflicts with data member")
        else:
            raise UnsupportedRepresentation(f"D{channel}: unsupported first allocation mapping {mapping!r}")
        plans.append((channel, storage, mapping, member, len(allocation) - 1))
    results = []
    for channel, storage, mapping, member, reserved_low_slots in plans:
        payload = archive.read(member) if mapping == DATA_MAPPING else bytes(len(packed[channel]))
        comparison = compare_packed(packed[channel], payload, samples)
        results.append({"channel": channel, "bit_order": "lsb_first",
                        "storage_form": "verified_1MiB_data_block" if mapping == DATA_MAPPING else "verified_uniform_LOW",
                        "allocation_mapping_first": mapping, "stored_samples": storage["stored_samples"],
                        "additional_verified_LOW_reservation_slots": reserved_low_slots,
                        "stored_tail_samples_beyond_logical_CSV": storage["stored_samples"] - samples,
                        "stored_tail_not_used_for_alignment": True,
                        "member": member if mapping == DATA_MAPPING else None,
                        "member_bytes": len(payload) if mapping == DATA_MAPPING else None,
                        "member_sha256": hashlib.sha256(payload).hexdigest() if mapping == DATA_MAPPING else None,
                        "member_CRC32": f"{archive.getinfo(member).CRC:08x}" if mapping == DATA_MAPPING else None,
                        "exact_logical_prefix_comparison": comparison})
    return results


def verify_case(marker_path, frequency=1000000):
    marker_sha = capture_sha256(marker_path)
    marker, csv_path, csv_sha, demo_path, demo_sha = marker_inputs(marker_path)
    packed, rate, metadata, activity = read_csv_packed(csv_path)
    demo = inspect_demo(demo_path)
    configuration = validate_configuration(metadata, demo, rate)
    with zipfile.ZipFile(demo_path) as archive:
        comparison = compare_demo(archive, demo, packed, metadata["sample_count"])
    measurements = []
    for channel in (0, 1):
        levels = bytearray()
        for value in packed[channel]:
            levels.extend(BYTE_LEVELS[value])
        del levels[metadata["sample_count"]:]
        measured = analyze_levels(levels, rate, frequency, 8)
        high, low = measured["paired_high_samples"]["mean"], measured["paired_low_samples"]["mean"]
        measurements.append({"channel": channel, "source_frequency_hz_nominal": frequency,
                             "high_mean_ns": high * 1e9 / rate if high is not None else None,
                             "low_mean_ns": low * 1e9 / rate if low is not None else None,
                             "duty_percent": measured["paired_time_weighted_duty_percent"],
                             "paired_measurements": measured})
    require(capture_sha256(csv_path) == csv_sha and capture_sha256(demo_path) == demo_sha and
            capture_sha256(marker_path) == marker_sha, "Artifacts changed during analysis; result rejected")
    equal = all(row["exact_logical_prefix_comparison"]["mismatch_count"] == 0 for row in comparison)
    transition_channels = [row["channel"] for row in activity if row["transitions"]]
    first_words = [sum(row["first_frame_levels"][index] << row["channel"] for row in activity)
                   for index in range(min(8, metadata["sample_count"]))]
    return {"status": "METADATA_AND_ALL_32_LOGICAL_EXPORT_SAMPLES_EQUAL" if equal else "EXPORT_SAMPLE_MISMATCH",
            "scope": "native_export_consistency_only_not_RAW_bus_or_physical_conversion_proof",
            "hardware_access": False, "firmware_fault_established": False,
            "marker": str(marker_path.resolve()), "marker_sha256": marker_sha,
            "csv": str(csv_path.resolve()), "csv_sha256": csv_sha,
            "demo": str(demo_path.resolve()), "demo_sha256": demo_sha,
            "configuration": configuration, "CSV_metadata": metadata,
            "all_32_comparisons": comparison, "total_logical_sample_channel_comparisons": 32 * metadata["sample_count"],
            "all_32_logical_exports_equal": equal, "all_32_activity": activity,
            "lane_origin_diagnostic": {"expected_transition_channels_from_wiring": [0, 1],
                                       "observed_CSV_transition_channels": transition_channels,
                                       "expected_transition_channel_set_equal": transition_channels == [0, 1],
                                       "first_up_to_8_sample_words_hex": [f"{word:08x}" for word in first_words],
                                       "first_frame_channels_ever_HIGH": [row["channel"] for row in activity
                                                                           if any(row["first_frame_levels"])],
                                       "physical_USB_lane_origin_verified": False},
            "D0_D1_paired_diagnostics": measurements,
            "whole_declared_logical_capture_preserved": True,
            "no_byte_rotation_offset_search_or_logical_sample_discard": True}


def analyze_marker_report(marker_path, frequency):
    try:
        return verify_case(marker_path, frequency)
    except (PendingExports, UnsupportedRepresentation, ValueError, ArithmeticError,
            KeyError, OSError, zipfile.BadZipFile) as error:
        status = "PENDING_EXPORT_COMPLETION" if isinstance(error, PendingExports) else (
            "UNSUPPORTED_STORAGE_MAPPING_PENDING" if isinstance(error, UnsupportedRepresentation) else "VERIFICATION_ERROR")
        return {"status": status, "marker": str(marker_path.resolve()), "error": str(error),
                "sample_consistency_verdict": "not_established", "hardware_access": False}


def report(markers, frequency):
    cases = [analyze_marker_report(path, frequency) for path in markers]
    return {"analysis": "native_Stream_CSV_demo_strict_all32_bitpacked_logical_prefix",
            "hardware_access": False, "frequency_hz_nominal": frequency,
            "tool_sha256": capture_sha256(Path(__file__)),
            "frozen_native_buffer_parser_sha256": capture_sha256(Path(__file__).with_name("native_buffer_analyze.py")),
            "frozen_paired_analyzer_sha256": capture_sha256(Path(__file__).with_name("analyze_duty_capture.py")),
            "cases": cases, "all_completed_exports_equal": bool(cases) and all(
                case["status"] == "METADATA_AND_ALL_32_LOGICAL_EXPORT_SAMPLES_EQUAL" for case in cases),
            "lane_origin_evidence_scope": "physical_channel_labels_in_native_exports_not_independent_RAW_USB",
            "supported_storage": "start0_first1MiB_LSB_data_or_verified_uniform_LOW; unknown mappings stay pending"}


def self_test():
    checks = []
    with tempfile.TemporaryDirectory(prefix="native-stream-offline-") as directory:
        base = Path(directory)
        csv_path, demo_path, marker_path = base / "known.csv", base / "known.demo", base / "known.complete.json"
        def make_case(samples=503, lanes=(0, 1), truncate=False, unknown=False, flip=None,
                      extra_data=False, wrong_saved_rate=False):
            initial = [0] * 32
            initial[31] = 1  # constant HIGH uses a data block, not an unverified HIGH sentinel.
            rows = ["; Sample rate: 50 MHz", f"; Sample count: {samples}",
                    "SystemTime, Time(s), " + ", ".join(f"channel {ch}" for ch in CHANNELS),
                    "t,0," + ",".join(map(str, initial))]
            state = initial[:]
            for index in range(1, samples, 25):
                for channel in lanes:
                    state[channel] ^= 1
                rows.append(f"t,{Decimal(index)/RATE}," + ",".join(map(str, state)))
            csv_path.write_text("\n".join(rows) + "\n", encoding="utf-8")
            packed, _, _, _ = read_csv_packed(csv_path)
            config = {"settingData": {"setHz": RATE + 0.9 if wrong_saved_rate else RATE,
                                      "setTime": 100, "isBuffer": False, "RLE": False,
                                      "thresholdLevel": 1.6, "triggerPosition": 50},
                      "isOne": False, "isInstantly": True, "isRoll": False, "isStopModeImmediate": True,
                      "isSimpleTrigger": True, "isAdvancedTrigger": False, "glitchRemoval": [],
                      "channelsSet": [{"id": ch, "enable": True, "triggerType": 1 if ch == 0 else 0}
                                      for ch in CHANNELS]}
            with zipfile.ZipFile(demo_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
                archive.writestr("channel.ini", f"SessionName=DLA32_Plus\nSamplingFrequency=50000\nSamplingDepth={samples}\nTriggerSamplingDepth=0\n")
                archive.writestr("set.ini", "\n".join(key + "=" + json.dumps(value) for key, value in config.items()))
                for channel in CHANNELS:
                    data = channel in lanes or channel == 31
                    mapping = DATA_MAPPING if data else LOW_MAPPING
                    if unknown and channel == 2:
                        mapping = "123,0"
                    extra_mapping = DATA_MAPPING if extra_data and channel == 0 else LOW_MAPPING
                    archive.writestr(f"{channel}/channel.ini", f"channel {channel}\n0\n{samples+8}\n{mapping}\n{extra_mapping}\n")
                    if data:
                        payload = bytearray(BLOCK_BYTES)
                        payload[:len(packed[channel])] = packed[channel]
                        if flip and channel == flip[0]:
                            payload[flip[1]//8] ^= 1 << (flip[1]%8)
                        if truncate and channel == lanes[0]:
                            payload = payload[:20]
                        archive.writestr(f"{channel}/0-0.bin", payload)
                        if extra_data and channel == 0:
                            archive.writestr("0/0-1.bin", bytes(BLOCK_BYTES))
            marker_path.write_text(json.dumps({"completed": True, "csv": csv_path.name, "demo": demo_path.name,
                                   "csv_sha256": capture_sha256(csv_path), "demo_sha256": capture_sha256(demo_path)}))
        make_case()
        result = verify_case(marker_path)
        assert result["all_32_logical_exports_equal"] and result["total_logical_sample_channel_comparisons"] == 503*32
        assert result["lane_origin_diagnostic"]["expected_transition_channel_set_equal"]
        assert result["configuration"]["requested_nominal_samples_from_rate_duration"] == "5000000"
        assert result["configuration"]["saved_trigger_depth_samples"] == "0"
        assert result["all_32_activity"][31]["high_samples"] == 503
        levels, rate, metadata = read_native_csv(csv_path, CHANNELS)
        packed, _, _, _ = read_csv_packed(csv_path)
        for channel in CHANNELS:
            expected = bytearray((503+7)//8)
            for index, level in enumerate(levels[channel]):
                expected[index//8] |= level << (index%8)
            assert expected == packed[channel]
        assert analyze_levels(levels[0], rate, 1000000, 8) == result["D0_D1_paired_diagnostics"][0]["paired_measurements"]
        checks.extend(["all32_exact_packed_matches_frozen_parser", "constant_LOW_and_HIGH_channels",
                       "variable_N_not_requested_duration", "Stream_no_Single_or_trigger_depth_equation",
                       "paired_results_identical_to_frozen_analyzer"])
        make_case(samples=401, lanes=(20, 21))
        shifted = verify_case(marker_path)
        assert shifted["all_32_logical_exports_equal"]
        assert shifted["lane_origin_diagnostic"]["observed_CSV_transition_channels"] == [20, 21]
        assert not shifted["lane_origin_diagnostic"]["expected_transition_channel_set_equal"]
        assert shifted["D0_D1_paired_diagnostics"][0]["paired_measurements"]["complete_paired_cycles"] == 0
        checks.append("shifted20_21_detected_without_repair")
        make_case(flip=(0, 502))
        bad = verify_case(marker_path)
        assert not bad["all_32_logical_exports_equal"]
        assert bad["all_32_comparisons"][0]["exact_logical_prefix_comparison"]["first_mismatch_sample"] == 502
        checks.append("last_logical_sample_mismatch_detected")
        make_case()
        csv_path.write_text(csv_path.read_text()+"\n")
        assert analyze_marker_report(marker_path, 1000000)["status"] == "VERIFICATION_ERROR"
        checks.append("completion_hash_mismatch_rejected")
        make_case(truncate=True)
        assert "truncated" in analyze_marker_report(marker_path, 1000000)["error"]
        checks.append("truncated_storage_rejected")
        make_case(unknown=True)
        assert analyze_marker_report(marker_path, 1000000)["status"] == "UNSUPPORTED_STORAGE_MAPPING_PENDING"
        checks.append("unknown_mapping_pending_without_guessed_offset")
        make_case(extra_data=True)
        assert analyze_marker_report(marker_path, 1000000)["status"] == "UNSUPPORTED_STORAGE_MAPPING_PENDING"
        checks.append("additional_data_mapping_pending_with_small_declared_N")
        make_case(wrong_saved_rate=True)
        assert "setHz differs" in analyze_marker_report(marker_path, 1000000)["error"]
        checks.append("fractional_saved_rate_rejected_without_truncation")
        marker_path.write_text(json.dumps({"completed": False}))
        assert analyze_marker_report(marker_path, 1000000)["status"] == "PENDING_EXPORT_COMPLETION"
        checks.append("unfinished_exports_pending_without_comparison")
    return {"self_test": "PASS", "hardware_access": False, "checks": checks}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--marker", type=Path)
    group.add_argument("--directory", type=Path)
    parser.add_argument("--frequency", type=int, default=1000000)
    parser.add_argument("--json", type=Path)
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    if args.self_test:
        result = self_test()
    else:
        if not (args.marker or args.directory):
            parser.error("Provide --marker or --directory")
        require(args.frequency > 0, "Nominal source frequency must be positive")
        markers = [args.marker] if args.marker else sorted(args.directory.glob("*.complete.json"))
        result = report(markers, args.frequency)
    if args.json:
        with args.json.open("x", encoding="utf-8") as destination:
            json.dump(result, destination, indent=2, ensure_ascii=False)
            destination.write("\n")
        print(json.dumps({"output": str(args.json), "cases": len(result.get("cases", [])),
                          "all_completed_exports_equal": result.get("all_completed_exports_equal"),
                          "self_test": result.get("self_test")}))
    else:
        print(json.dumps(result, indent=2, ensure_ascii=False))
    if not args.self_test and not result["all_completed_exports_equal"]:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
