"""Inspect official FNIRSI event CSV and compare same-capture single-channel BIN.

Offline only. The CSV declares Fs and sample count; event times must fall exactly
on that grid. States hold from an event until the next event or declared end.
Incomplete endpoint PWM cycles are excluded by the unchanged paired analyzer.
No hardware, native GUI, firmware, acceptance criterion or driver is accessed.
"""

import argparse
import csv
from decimal import Decimal
import io
import json
from pathlib import Path
import re
import tempfile
import zipfile

from analyze_duty_capture import analyze_levels, capture_sha256


def parse_quantity(text, rate=False):
    match = re.fullmatch(r"\s*([0-9]+(?:\.[0-9]+)?)\s*([kKMGT]?)(Hz)?\s*", text)
    if not match or bool(match[3]) != rate:
        raise ValueError(f"Invalid {'rate' if rate else 'sample count'}: {text!r}")
    multiplier = {"": 1, "k": 1000, "K": 1000, "M": 1000000,
                  "G": 1000000000, "T": 1000000000000}[match[2]]
    value = Decimal(match[1]) * multiplier
    if value <= 0 or value != int(value):
        raise ValueError("Expected positive integer rate/count")
    return int(value)


def read_native_csv(path, channels):
    metadata = {}
    events = []
    with path.open("r", encoding="utf-8-sig", newline="") as source:
        for line in source:
            if line.startswith(";"):
                text = line[1:].strip()
                if ":" in text and not text.startswith("CSV, generated by "):
                    key, value = text.split(":", 1)
                    metadata[key.strip()] = value.strip()
                continue
            if not line.strip():
                continue
            reader = csv.reader(io.StringIO(line + source.read()), skipinitialspace=True)
            header = next(reader)
            if len(header) < 3 or [v.strip() for v in header[:2]] != ["SystemTime", "Time(s)"]:
                raise ValueError("Expected official waveform CSV with SystemTime, Time(s) columns")
            column_channels = {}
            for index, label in enumerate(header[2:], 2):
                match = re.fullmatch(r"channel\s+(\d+)", label.strip())
                if not match or int(match[1]) in column_channels:
                    raise ValueError("Ambiguous physical channel CSV columns")
                column_channels[int(match[1])] = index
            if any(channel not in column_channels for channel in channels):
                raise ValueError("Selected channel is absent from native CSV")
            rate = parse_quantity(metadata["Sample rate"], rate=True)
            samples = parse_quantity(metadata["Sample count"])
            previous_index = -1
            previous_full_values = None
            for number, row in enumerate(reader, 1):
                if not row or all(not cell.strip() for cell in row):
                    continue
                if len(row) != len(header):
                    raise ValueError(f"CSV event {number}: wrong column count")
                exact_index = Decimal(row[1].strip()) * rate
                if exact_index != int(exact_index):
                    raise ValueError(f"CSV event {number}: timestamp is not exactly on declared sample grid")
                index = int(exact_index)
                if not 0 <= index <= samples or index < previous_index:
                    raise ValueError(f"CSV event {number}: timestamp outside capture or not monotone")
                full_values = tuple(int(cell.strip()) for cell in row[2:])
                if any(value not in (0, 1) for value in full_values):
                    raise ValueError(f"CSV event {number}: non-binary level")
                if index == previous_index:
                    if full_values != previous_full_values:
                        raise ValueError(f"CSV event {number}: conflicting states at same sample")
                    continue
                values = {channel: int(row[column_channels[channel]].strip()) for channel in channels}
                events.append((index, values))
                previous_index, previous_full_values = index, full_values
            break
        else:
            raise ValueError("CSV contains no event header")
    if not events or events[0][0] != 0:
        raise ValueError("CSV does not establish all selected initial states at sample 0")
    levels = {channel: bytearray(samples) for channel in channels}
    for event_number, (start, values) in enumerate(events):
        end = events[event_number + 1][0] if event_number + 1 < len(events) else samples
        for channel in channels:
            levels[channel][start:end] = bytes([values[channel]]) * (end - start)
    return levels, rate, {
        "headers": metadata, "sample_count": samples, "event_rows": len(events),
        "last_event_sample": events[-1][0], "physical_channels": sorted(column_channels),
        "sample_count_provenance": "native_CSV_declared_header_not_independent_physical_USB_count",
        "time_grid_validation": "all_event_times_exact_integer_samples_at_declared_Fs",
        "reconstruction": "sample_0_initial_state_then_hold_each_event_state_until_next_event_or_declared_end",
        "capture_duration_ms": samples * 1000 / rate,
    }


def compare_bit_payload(payload, levels, stored_samples=None):
    payload_samples = stored_samples if stored_samples is not None else len(levels)
    if payload_samples < len(levels):
        raise ValueError("Bit payload is shorter than the logical CSV capture")
    expected_bytes = (payload_samples + 7) // 8
    if len(payload) != expected_bytes:
        raise ValueError(f"Single-channel BIN size {len(payload)} differs from expected {expected_bytes}")
    candidates = []
    for order in ("lsb_first", "msb_first"):
        mismatch_count = 0
        first = None
        for index, expected in enumerate(levels):
            shift = index % 8 if order == "lsb_first" else 7 - index % 8
            actual = (payload[index // 8] >> shift) & 1
            if actual != expected:
                mismatch_count += 1
                if first is None:
                    first = {"sample": index, "CSV": expected, "BIN": actual}
        candidates.append({"bit_order": order, "mismatch_count": mismatch_count,
                           "first_mismatch": first})
    matches = [candidate["bit_order"] for candidate in candidates if candidate["mismatch_count"] == 0]
    return {"bytes": len(payload), "expected_bytes": expected_bytes,
            "payload_declared_samples": payload_samples,
            "compared_logical_CSV_samples": len(levels),
            "additional_stored_tail_samples_not_compared": payload_samples - len(levels),
            "unused_final_padding_bits_not_compared": expected_bytes * 8 - payload_samples,
            "candidates": candidates, "exact_match_bit_orders": matches,
            "unique_bit_order_established_for_this_pair": len(matches) == 1}


def compare_single_bin(path, levels, stored_samples=None):
    payload = path.read_bytes()
    actual_stored = None
    provenance = "logical_CSV_sample_count"
    if len(payload) != (len(levels) + 7) // 8 and stored_samples is not None:
        actual_stored = stored_samples
        provenance = "same_capture_demo_channel_ini_stored_sample_count"
    return {"path": str(path.resolve()), "sha256": capture_sha256(path),
            "sample_count_provenance": provenance,
            **compare_bit_payload(payload, levels, actual_stored)}


def inspect_demo(path):
    result = {"path": str(path.resolve()), "sha256": capture_sha256(path),
              "bytes": path.stat().st_size}
    with path.open("rb") as source:
        result["first_32_bytes_hex"] = source.read(32).hex()
    result["zip_container"] = zipfile.is_zipfile(path)
    if result["zip_container"]:
        with zipfile.ZipFile(path) as archive:
            result["members"] = [{"name": item.filename, "bytes": item.file_size,
                                  "compressed_bytes": item.compress_size} for item in archive.infolist()]
            for name, key in (("channel.ini", "session_metadata"), ("set.ini", "saved_configuration")):
                if name in archive.namelist():
                    contents = archive.read(name).decode("utf-8-sig")
                    parsed = {}
                    for line in contents.splitlines():
                        if "=" in line:
                            label, value = line.split("=", 1)
                            if value.startswith(("[", "{")):
                                value = json.loads(value)
                            elif value in ("true", "false"):
                                value = value == "true"
                            parsed[label] = value
                    result[key] = parsed
            storage = {}
            for name in archive.namelist():
                match = re.fullmatch(r"(\d+)/channel\.ini", name)
                if match:
                    lines = archive.read(name).decode("utf-8-sig").splitlines()
                    if len(lines) < 3:
                        raise ValueError("Incomplete demo channel metadata")
                    storage[match[1]] = {"label": lines[0], "start_sample": int(lines[1]),
                                         "stored_samples": int(lines[2]),
                                         "allocation_lines": len(lines) - 3}
            result["channel_storage_metadata"] = storage
    return result


def analyze(path, channels, frequency, bins, demo):
    levels, rate, metadata = read_native_csv(path, channels)
    demo_metadata = inspect_demo(demo) if demo else None
    rows = []
    for channel in channels:
        measured = analyze_levels(levels[channel], rate, frequency, 8)
        high = measured["paired_high_samples"]["mean"]
        low = measured["paired_low_samples"]["mean"]
        storage = (demo_metadata or {}).get("channel_storage_metadata", {}).get(str(channel))
        rows.append({"channel": channel, "sample_count": len(levels[channel]),
                     "high_mean_ns": high * 1e9 / rate if high is not None else None,
                     "low_mean_ns": low * 1e9 / rate if low is not None else None,
                     "duty_percent": measured["paired_time_weighted_duty_percent"],
                     "paired_measurements": measured,
                     "single_channel_bin_comparison": compare_single_bin(
                         bins[channel], levels[channel], storage["stored_samples"] if storage else None)
                     if channel in bins else None})
    return {"analysis": "official_FNIRSI_waveform_event_CSV_offline_paired_cycles",
            "classification": "diagnostic_only_no_new_acceptance_criteria",
            "hardware_access": False, "firmware_fault_established": False,
            "csv": str(path.resolve()), "csv_sha256": capture_sha256(path),
            "tool_sha256": capture_sha256(Path(__file__)),
            "paired_analyzer_sha256": capture_sha256(Path(__file__).with_name("analyze_duty_capture.py")),
            "sampling_rate_hz": rate, "nominal_source_frequency_hz": frequency,
            "native_export_metadata": metadata,
            "native_hover_duty_not_used_as_statistical_input": True,
            "paired_definition": "rising, falling, next rising; endpoint partial cycles excluded; duty total_HIGH/total_period",
            "rows": rows, "demo": demo_metadata}


def self_test():
    with tempfile.TemporaryDirectory(prefix="fnirsi-native-buffer-offline-") as directory:
        base = Path(directory)
        path = base / "fixture.csv"
        path.write_text("; Sample rate: 50 MHz\n; Sample count: 500\n"
                        "SystemTime, Time(s), channel 0, channel 31\n"
                        "t,0,0,1\n" + "".join(
                            f"t,{Decimal(index)/50000000},{level},{1-level}\n"
                            for cycle in range(9) for index, level in
                            ((1 + 50*cycle, 1), (26 + 50*cycle, 0))) +
                        "t,0.000009020,1,0\n", encoding="utf-8")
        levels, rate, meta = read_native_csv(path, [0, 31])
        assert len(levels[0]) == 500 and rate == 50000000
        assert all(a != b for a, b in zip(levels[0], levels[31]))
        measured = analyze_levels(levels[0], rate, 1000000, 0)
        assert measured["complete_paired_cycles"] == 9
        assert measured["paired_time_weighted_duty_percent"] == 50
        for order in ("lsb_first", "msb_first"):
            payload = bytearray(63)
            for index, value in enumerate(levels[0]):
                shift = index % 8 if order == "lsb_first" else 7-index % 8
                payload[index//8] |= value << shift
            binary = base / f"fixture-{order}.bin"
            binary.write_bytes(payload)
            comparison = compare_single_bin(binary, levels[0])
            assert comparison["exact_match_bit_orders"] == [order]
            assert comparison["unused_final_padding_bits_not_compared"] == 4
        binary.write_bytes(payload + b"\xff")
        comparison = compare_single_bin(binary, levels[0], 508)
        assert comparison["exact_match_bit_orders"] == ["msb_first"]
        assert comparison["additional_stored_tail_samples_not_compared"] == 8
        assert comparison["unused_final_padding_bits_not_compared"] == 4
        binary.write_bytes(payload[:-1])
        try:
            compare_single_bin(binary, levels[0])
        except ValueError:
            pass
        else:
            raise AssertionError("Wrong BIN length accepted")
        original = path.read_text()
        for altered in (original.replace("t,0,0,1", "t,0.000000010,0,1"),
                        original.replace("t,0,0,1", "t,0,2,1"),
                        original.replace("t,0,0,1", "t,0.000000020,0,1")):
            path.write_text(altered)
            try:
                read_native_csv(path, [0, 31])
            except ValueError:
                pass
            else:
                raise AssertionError("Malformed native event CSV accepted")
    return {"self_test": "PASS", "hardware_access": False,
            "checks": ["exact_grid_event_reconstruction", "physical_channel_31", "paired_cycles",
                       "both_BIN_bit_orders", "final_byte_padding", "invalid_size_grid_level_initial_state"]}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("csv", nargs="?", type=Path)
    parser.add_argument("--channels", default="0,1")
    parser.add_argument("--frequency", type=int, default=1000000)
    parser.add_argument("--bin", action="append", default=[], metavar="CHANNEL=PATH")
    parser.add_argument("--demo", type=Path)
    parser.add_argument("--json", type=Path)
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    if args.self_test:
        print(json.dumps(self_test()))
        return
    if args.csv is None or args.frequency <= 0:
        parser.error("Specify CSV and positive source frequency, or --self-test")
    channels = [int(value) for value in args.channels.split(",")]
    if len(set(channels)) != len(channels) or any(not 0 <= channel <= 31 for channel in channels):
        parser.error("Channels must be unique physical indices 0..31")
    bins = {}
    for value in args.bin:
        channel, path = value.split("=", 1)
        channel = int(channel)
        if channel not in channels or channel in bins:
            parser.error("BIN channel must be selected once")
        bins[channel] = Path(path)
    output = args.json or args.csv.with_suffix(".native-analysis.json")
    if output.exists():
        parser.error(f"Refusing to overwrite existing output: {output}")
    report = analyze(args.csv, channels, args.frequency, bins, args.demo)
    with output.open("x", encoding="utf-8", newline="\n") as destination:
        json.dump(report, destination, indent=2, allow_nan=False)
        destination.write("\n")
    print(json.dumps({"json": str(output), "Fs": report["sampling_rate_hz"],
                      "samples": report["native_export_metadata"]["sample_count"],
                      "event_rows": report["native_export_metadata"]["event_rows"],
                      "rows": [{key: row[key] for key in
                                ("channel", "high_mean_ns", "low_mean_ns", "duty_percent",
                                 "single_channel_bin_comparison")} for row in report["rows"]]}))


if __name__ == "__main__":
    main()
